### ISSUE TITLE
Licence Decision

### ISSUE THREAD

**Issue by dcdarrell9** [dcdarrell9/scratch-map#11]
**Describe the solution you'd like**
- The most appropriate licence for the project

**Describe alternatives you've considered**
- None

**Additional context**
- https://help.github.com/en/articles/licensing-a-repository
- Read through and find which seems the most applicable, once that's in, we'll review as a team

**Comment by treilly94** [comment]
Picked a licence using https://choosealicense.com/
Went for https://choosealicense.com/licenses/gpl-3.0/ as it will allow people to use the code but not to create closed source versions.

**Comment by treilly94** [comment]
Created pull request #16

**Comment by dcdarrell9** [comment]
Sounds good to me
