### ISSUE TITLE
Definition of Done/Ready

### ISSUE THREAD

**Issue by dcdarrell9** [dcdarrell9/scratch-map#13]
**Describe the solution you'd like**
- Have a draft definition of done/ready

**Additional context**
- Basic defintions ready to be reviewed as a team
- Think of adding labels into issues

**Comment by treilly94** [comment]
I'd say that "has been tested locally" and "passes all tests" are kinda the same thing. 
But looks good, can always change it as we go if needs be

**Comment by dcdarrell9** [comment]
Probably should be worded like 'locally all runs/tested' 'ci/cd analysis all successful'
