### ISSUE TITLE
Create a Wiki

### ISSUE THREAD

**Issue by dcdarrell9** [dcdarrell9/scratch-map#2]
**Describe the solution you'd like**
- Create a basic wiki just explaining what this application will do. Maybe describe some of the tools to be looked into

**Describe alternatives you've considered**
- None

**Additional context**
- First run of Wiki, will change over time

**Comment by treilly94** [comment]
Looks like Github wiki cant do a directory structure at the min. Thats going to make the whole thing a real mess. It might be worth just putting all the markdown in a docs or wiki directory

https://stackoverflow.com/questions/11088285/github-wiki-directories

**Comment by treilly94** [comment]
created a branch called docs and added in some markdown files to contain the wiki

**Comment by dcdarrell9** [comment]
I removed the wiki, like the docs folder
