### ISSUE TITLE
Research - Kotlin

### ISSUE THREAD

**Issue by srussell91** [dcdarrell9/scratch-map#22]
**Describe the solution you'd like**
Understand the pros/cons of developing this sort of app in Kotlin

**Describe alternatives you've considered**
Python
Javascript
ReactJS

**Additional context**

**Comment by srussell91** [comment]
**Possible solution**
[KVision](https://github.com/rjaros/kvision) is an open source object oriented web framework for Kotlin/JS.

**Pros**
- Integration interface for Ktor, Jooby and Spring Boot frameworks on the server side, front and back end can share common code.
- Integrates with a whole bunch of common web libraries and components.
- Support for building cross-platform, desktop applications with Electron.
- Massive source of [examples](https://github.com/rjaros/kvision-examples), great [documentation](https://kvision.gitbook.io/kvision-guide/), full api [documentation](https://rjaros.github.io/kvision/api/)

**Cons**
- Still in active development / relatively infancy
- Only targets web and desktop, no mobile
- More akin to GUI programming / unfamiliar web development workflow

**Comment by dcdarrell9** [comment]
Cool, I've not done much with Kotlin (I'm guessing none of us have really) But it seems like it's not fully there yet to me, although I could be wrong.

Handy little piece explaining some stuff about whether or not it should be used, seems like there's nothing stopping it, and it can be run alongside Java, and seems to work well with Android  (possibly easy app integration?)
https://hackernoon.com/kotlin-in-production-should-you-stay-or-should-you-go-a3428b44b236

It could be worth having a trial run to see how easy/simple it would be to set up an application, similar to what Flask would do and then being able to run it then alongside some other tools like google maps api (https://www.raywenderlich.com/230-introduction-to-google-maps-api-for-android-with-kotlin)

My personal preference wouldn't be Kotlin, but I would like to learn it as chances are it's going to be huge

**Comment by dcdarrell9** [comment]
Going with Python Flask
