### ISSUE TITLE
Review Issue/Bug Template

### ISSUE THREAD

**Issue by dcdarrell9** [dcdarrell9/scratch-map#5]
**Describe the solution you'd like**
- Templates for various parts of the project 

**Describe alternatives you've considered**
- Issues
- Test
- Standard
- Help
- Pull Requests

**Additional context**
- The templates are currently the basic ones from Github
- I'd like them to be reviewed and changed to be more suitable for the project
- Feel free to add any so that we can review as a team to see whether they're applicable

**Comment by emilioward** [comment]
@dcdarrell9 @treilly94 Is this still valid. I can see templates for issues/bugs in the repo already?

**Comment by dcdarrell9** [comment]
@emilioward yeah still valid, more about refining them and then adding anything that's missing

**Comment by dcdarrell9** [comment]
Leave them as is, change as we go.
