### ISSUE TITLE
Research - ReactJS

### ISSUE THREAD

**Issue by dcdarrell9** [dcdarrell9/scratch-map#6]
**Describe the solution you'd like**
- Research suitability for React.

**Describe alternatives you've considered**
- Other cards have been added to see suitability

**Additional context**
- Test startup guides and write notes so that everyone will have 'the same' startup

**Comment by emilioward** [comment]
The best startup guide for react is Facebooks own one located here:

https://facebook.github.io/create-react-app/docs/getting-started

React is difficult to learn if you don't have any prior javascript knowledge as it would be difficult to distinguish between what is actually vanilla javascript and what is react.js. 

React would be very powerful to create a single page web app onto we would have to also learn things like jasmine.js and jest.js for thing like unit and behavioural testing. But it would be a quick app to run and test straight from the browser. 

Mocha - https://mochajs.org/
Jest- https://jestjs.io/
Jasmine - https://jasmine.github.io/ 

Redux for state management in react, graphql (https://graphql.org/) to develop api's. 

This guy is a good youtuber and he has loads of tutorials one of which is react.js for beginners (https://www.youtube.com/watch?v=sBws8MSXN7A)

**Comment by dcdarrell9** [comment]
@emilioward Sounds decent, any ideas on the following...

How well does it work with the google maps api? 

What about if we wanted to add some python/java backend? How well does it integrate?

Is it easy to add/modify layouts like if we wanted to have something like home/map/info and then we wanted to use things on the map (like dropping a pin location)?

Does it work well with any database stuff like postgres?

**Comment by emilioward** [comment]
@dcdarrell9 Just doing a quick google search and I can find loads of results for people integrating react.js with google maps api's (https://scotch.io/tutorials/react-apps-with-the-google-maps-api-and-google-maps-react)

I have done a little research for other projects where I was looking to integrate django/flask with reac.js so i know it can be done. (But I don't have any experience though, but it would be fun to learn)

Pages, buttons, maps etc would all be there own separate components so it would be easy to manipulate and modify if need be, without it breaking everything else on the page. Think that can be seen on the link above.

I'm not 100% sure on postgres integration with it, would have to look into that a bit more, but I would be surprised if you couldn't

**Comment by treilly94** [comment]
The project I'm on at work is a nodejs app that uses Mocha, Jasmine, and graphql. 
Would be interesting seeing all that stuff from a developers perspective

**Comment by dcdarrell9** [comment]
Going with Python Flask
