### ISSUE TITLE
Research - Javascript

### ISSUE THREAD

**Issue by dcdarrell9** [dcdarrell9/scratch-map#7]
**Describe the solution you'd like**
- Research suitability for Javascript.

**Describe alternatives you've considered**
- Other cards have been added to see suitability

**Additional context**
- Test startup guides and write notes so that everyone will have 'the same' startup

**Comment by treilly94** [comment]
The PWA starter kit may be a good starting point for a javascript app
https://pwa-starter-kit.polymer-project.org/overview

**Comment by dcdarrell9** [comment]
Going with Pythin Flask
