### ISSUE TITLE
Research - Build tool

### ISSUE THREAD

**Issue by treilly94** [dcdarrell9/scratch-map#8]
**Describe the solution you'd like**
Decide on an appropiate build tool for the project.
This will be dependent on the language we use.

**Describe alternatives you've considered**

**Additional context**

**Comment by dcdarrell9** [comment]
Check out pull panda https://github.co/31G3b4T

**Comment by treilly94** [comment]
Makefiles to get moving?

**Comment by dcdarrell9** [comment]
^^ Makefiles.
